import Mathlib

namespace LogicalBell

/-- Abstract recovery-free CHSH protocol after local deletion noise. -/
structure Protocol where
  dummy : Unit

/-- Abstract quantum state. -/
structure QState where
  dummy : Unit

/-- Abstract quantum channel. -/
structure QChannel where
  dummy : Unit

/-- Survival probability corresponding to deletion probability `p`. -/
def survival (p : ℝ) : ℝ := 1 - p

/-- Abstract independent flagged deletion channel with survival probability `eta`. -/
def deletionChannel (_eta : ℝ) : QChannel := ⟨()⟩

/-- Final Alice--Bob state generated by protocol `P` after Bob-side deletion probability `p`. -/
def postDeletionState (_P : Protocol) (_p : ℝ) : QState := ⟨()⟩

/-- The channel admits a symmetric two-output extension. -/
opaque ChannelTwoExtendible : QChannel → Prop

/-- The state is two-extendible on Bob's side. -/
opaque StateTwoExtendible : QState → Prop

/-- Absolute CHSH value of the final state under the protocol's chosen measurements. -/
opaque chshValue : QState → ℝ

/-- Routing-extension lemma: deletion is two-extendible for `0 ≤ eta ≤ 1/2`. -/
axiom deletion_twoExtendible :
    ∀ {eta : ℝ},
      0 ≤ eta → eta ≤ (1 : ℝ) / 2 →
        ChannelTwoExtendible (deletionChannel eta)

/-- Applying a two-extendible Bob-side deletion channel gives a two-extendible output state. -/
axiom postDeletion_twoExtendible :
    ∀ {P : Protocol} {p eta : ℝ},
      eta = survival p →
      ChannelTwoExtendible (deletionChannel eta) →
        StateTwoExtendible (postDeletionState P p)

/-- CHSH-monogamy / two-setting shareability bound. -/
axiom twoExtendible_chsh_bound :
    ∀ {rho : QState},
      StateTwoExtendible rho → chshValue rho ≤ (2 : ℝ)

lemma survival_nonneg_of_le_one {p : ℝ} (hp1 : p ≤ 1) :
    0 ≤ survival p := by
  unfold survival
  linarith

lemma survival_le_half_of_half_deletion {p : ℝ}
    (hhalf : (1 : ℝ) / 2 ≤ p) :
    survival p ≤ (1 : ℝ) / 2 := by
  unfold survival
  linarith

lemma erasure_branch_nonneg_of_survival_le_half {eta : ℝ}
    (heta_half : eta ≤ (1 : ℝ) / 2) :
    0 ≤ 1 - 2 * eta := by
  linarith

/-- Theorem 3: universal recovery-free CHSH no-go at half deletion. -/
theorem theorem3_universal_no_go
    (P : Protocol) {p : ℝ}
    (_hp0 : 0 ≤ p) (hp1 : p ≤ 1)
    (hhalf : (1 : ℝ) / 2 ≤ p) :
    chshValue (postDeletionState P p) ≤ (2 : ℝ) := by
  have heta_nonneg : 0 ≤ survival p :=
    survival_nonneg_of_le_one hp1
  have heta_half : survival p ≤ (1 : ℝ) / 2 :=
    survival_le_half_of_half_deletion hhalf
  have hchan : ChannelTwoExtendible (deletionChannel (survival p)) :=
    deletion_twoExtendible heta_nonneg heta_half
  have hstate : StateTwoExtendible (postDeletionState P p) :=
    postDeletion_twoExtendible (P := P) (p := p) (eta := survival p) rfl hchan
  exact twoExtendible_chsh_bound hstate

/-- Equivalent survival-probability version. -/
theorem theorem3_universal_no_go_eta
    (P : Protocol) {p eta : ℝ}
    (hp1 : p ≤ 1)
    (heta : eta = survival p)
    (heta_half : eta ≤ (1 : ℝ) / 2) :
    chshValue (postDeletionState P p) ≤ (2 : ℝ) := by
  have heta_nonneg : 0 ≤ eta := by
    rw [heta]
    exact survival_nonneg_of_le_one hp1
  have hchan : ChannelTwoExtendible (deletionChannel eta) :=
    deletion_twoExtendible heta_nonneg heta_half
  have hstate : StateTwoExtendible (postDeletionState P p) :=
    postDeletion_twoExtendible (P := P) (p := p) (eta := eta) heta hchan
  exact twoExtendible_chsh_bound hstate

end LogicalBell
